export const theme = {
  colors: {
    tamrillo: "#8A1325",
    marigold: "#DEBF39",
    plum: "#4E1670",
    cottonSeed: "#B8B4AD",
    // lightGrey: 'rgb(241 245 249)',
    lightGrey: "#e1dfdc",
    lighterGrey: "#B8B4AD",
    midGrey: "#9d988e",
    grey: "#6b665d",
    darkGrey: "#403d38",
    // lighterGrey: '#CCC',
    // midGrey: '#999',
    // grey: '#666',
    charcoal: "#333",
    white: "#fff",
    black: "#000",
  },
  fonts: {
    mono: "ui-monospace, Menlo, Monaco, 'Cascadia Mono', 'Segoe UI Mono', 'Roboto Mono', 'Oxygen Mono', 'Ubuntu Monospace', 'Source Code Pro', 'Fira Mono', 'Droid Sans Mono', 'Courier New', monospace",
    display: "Playfair Display, serif",
    serif: "Merriweather, serif",
  },
  sizes: {
    xs: "0.75rem",
    sm: "1rem",
    md: "1.25rem",
    lg: "2rem",
    xlg: "3rem",
    xxlg: "5rem",
  },
  breakpoints: {
    xs: 320,
    sm: 425,
    md: 768,
    lg: 1024,
    xlg: 1440,
  },
  spacers: {
    xs: "0.5rem",
    sm: "1rem",
    md: "1.5rem",
    lg: "2rem",
    xlg: "3rem",
    xxlg: "5rem",
  },
  layout: {
    maxWidthXlg: "60rem",
    maxWidthLg: "48rem",
    maxWidthSm: "36rem",
  },
};
