// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import MenuItems from './MenuItems';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	Image,
	MenuItems,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	menu_item: MenuItems,
	quote: Quote,
	text: Text,
};
