// Code generated by Slice Machine. DO NOT EDIT.

import ArticleList from './ArticleList';
import ContactForm from './ContactForm';
import Image from './Image';
import MenuItems from './MenuItems';
import Quote from './Quote';
import Text from './Text';
import WeeklySpecials from './WeeklySpecials';

export {
	ArticleList,
	ContactForm,
	Image,
	MenuItems,
	Quote,
	Text,
	WeeklySpecials,
};

export const components = {
	article_list: ArticleList,
	contact_form: ContactForm,
	image: Image,
	menu_item: MenuItems,
	quote: Quote,
	text: Text,
	weekly_specials: WeeklySpecials,
};
